Repository SharonIV0x86/CinderPeak, pull requests merged in 2025-09, with the labels that each got.

#66 feat(refactor): Refactored redundant addEdge function overloads over entire code base.
  examples/ListExample1.cpp
  examples/PrimitiveGraph.cpp
  src/GraphList.hpp
  src/GraphMatrix.hpp
  src/PeakStore.hpp
  src/StorageEngine/AdjacencyList.hpp
  src/StorageInterface.hpp
Labels: enhancement, Level 2, gssoc25

#83 feat(GraphList): Implemented updateEdge method to update edge weight.
  examples/ListExample1.cpp
  src/GraphList.hpp
  src/PeakStore.hpp
  src/StorageEngine/AdjacencyList.hpp
  src/StorageEngine/HybridCSR_COO.hpp
  src/StorageInterface.hpp
  tests/AdjacencyShard.cpp
  tests/HybridCSRCOO.cpp
Labels: enhancement, Level 2, gssoc25

#87 feat(GraphList): added removeVertex() function in GraphList.
  .gitignore
  src/GraphList.hpp
  src/PeakStore.hpp
  src/StorageEngine/AdjacencyList.hpp
  src/StorageEngine/HybridCSR_COO.hpp
  src/StorageEngine/Utils.hpp
  src/StorageInterface.hpp
  tests/AdjacencyShard.cpp
  tests/HybridCSRCOO.cpp
Labels: enhancement, Level 2, gssoc25, Under Review

#92 feat(API): upgrading API usage.
  examples/ListExample1.cpp
  examples/MatrixExample.cpp
  examples/PrimitiveGraph.cpp
  scripts/auto-format.bat
  scripts/auto-format.py
  src/GraphList.hpp
  src/GraphMatrix.hpp
  src/StorageEngine/AdjacencyList.hpp
Labels: enhancement

#93 feat(GraphList): added ``clearEdges()`` method to remove all the edges
  examples/ListExample1.cpp
  src/GraphList.hpp
  src/PeakStore.hpp
  src/StorageEngine/AdjacencyList.hpp
  src/StorageEngine/HybridCSR_COO.hpp
  src/StorageInterface.hpp
  tests/AdjacencyShard.cpp
  tests/HybridCSRCOO.cpp
Labels: enhancement, Level 2, gssoc25, Under Review

#96 feat(ci + tests): Restructure Tests and Update CI + CMake
  CMakeLists.txt
  src/GraphList.hpp
  src/PeakStore.hpp
  tests/integration/GraphList/GraphListShard.cpp
  tests/integration/GraphMatrix/GraphMatixShard.cpp
  tests/tests.cpp
  tests/unit/AdjacencyList/AdjacencyShard.cpp
  tests/unit/HybridCSR_COO/HybridCSRCOO.cpp
  tests/unit/Statistics/Statistics.cpp
Labels: enhancement, Under Review
