Repository SharonIV0x86/CinderPeak, pull requests merged in 2025-10, with the labels that each got.

#99 feat(GraphList): added ``removeEdge()`` method to remove an edge
  examples/ListExample1.cpp
  src/GraphList.hpp
  src/PeakStore.hpp
  src/StorageEngine/AdjacencyList.hpp
  src/StorageEngine/HybridCSR_COO.hpp
  src/StorageInterface.hpp
  tests/unit/AdjacencyList/AdjacencyShard.cpp
  tests/unit/HybridCSR_COO/HybridShard.cpp
Labels: enhancement, Level 2, gssoc25, Under Review

#106 feat(examples): Refactor examples: move files to GraphList, GraphMatrix and Experimental.
  CMakeLists.txt
  examples/GraphList/ListExample1.cpp
  examples/GraphList/PrimitiveGraph.cpp
  examples/GraphList/addEdge_usage.cpp
  examples/GraphList/addVertex_usage.cpp
  examples/GraphList/clearEdges_usage.cpp
  examples/GraphList/getEdge_usage.cpp
  examples/GraphList/hasVertex_usage.cpp
  examples/GraphList/numEdges_usage.cpp
  examples/GraphList/numVertices_usage.cpp
  examples/GraphList/removeEdge_usage.cpp
  examples/GraphList/removeVertex_usage.cpp
  examples/GraphList/setConsoleLogging_usage.cpp
  examples/GraphList/updateEdge_usage.cpp
  examples/GraphMatrix/MatrixExample.cpp
  examples/GraphMatrix/addEdge_usage.cpp
  examples/GraphMatrix/addVertex_usage.cpp
  examples/GraphMatrix/getEdge_usage.cpp
  examples/GraphMatrix/getGraphStatistics_usage.cpp
  examples/GraphMatrix/removeVertex_usage.cpp
  examples/Policies/PoliciesExample.cpp
  examples/experimental/HybridExample.cpp
  examples/experimental/LogExample.cpp
  examples/experimental/PeakExample.cpp
Labels: enhancement, good first issue, Level 2, gssoc25, High Priority, hacktoberfest

#112 feat(policies) Add tests for Throw + Silent policy
  src/PeakLogger.hpp
  src/PolicyConfiguration.hpp
  tests/unit/Policies/EPShard_ThrowAndSilent.cpp
Labels: enhancement, good first issue, Under Review, hacktoberfest
