Repository SharonIV0x86/CinderPeak, pull requests merged in 2025-08, with the labels that each got.

#15 feat(repo): Added covenant code of conduct.
  CODE_OF_CONDUCT.md
Labels: Level 1, GSSoC 2025

#24 feat(adjlist): Enhance implementation of `impl_doesEdgeExist` function
  src/StorageEngine/AdjacencyList.hpp
Labels: enhancement, Level 2, GSSoC 2025

#33 bug(license): The link in the mit license is not working.
  README.md
Labels: bug, Level 1, GSSoC 2025

#31 feat(exceptions): Revamp exception handling in CinderPeak
  src/CinderExceptions.hpp
Labels: enhancement, Level 2, gssoc25

#26 feat(docs): Documentation for Hybrid CSR-COO Storage Format.
  docs/hybrid_storage.md
Labels: enhancement, Level 3, gssoc25

#43 fix(hybrid): Performance Issues in HybridCSR_COO Implementation
  scripts/install-hooks.sh
  src/StorageEngine/GraphContext.hpp
  src/StorageEngine/HybridCSR_COO.hpp
  tests/HybridCSRCOO.cpp
Labels: enhancement, good first issue, Level 3, gssoc25

#50 feat(docs): Add Usage Guide for CinderPeak
  docs/usage.md
Labels: documentation, enhancement, Level 2, gssoc25

#56 feat(hybrid): Added unit tests for HybridCSR_COO storage format
  tests/HybridCSRCOO.cpp
Labels: enhancement, Level 2, gssoc25

#58 chore(storage): formatted files using clang-format and removed comments.
  .github/workflows/build.yml
  .github/workflows/ci.yml
  examples/extras/HybridExample.cpp
  examples/extras/LogExample.cpp
  examples/extras/PeakExample.cpp
  src/CinderExceptions.hpp
  src/CinderPeak.hpp
  src/PeakLogger.hpp
  src/PeakStore.hpp
  src/StorageEngine/AdjacencyList.hpp
  src/StorageEngine/GraphContext.hpp
  src/StorageEngine/HybridCSR_COO.hpp
  src/StorageInterface.hpp
  src/Visualizer.hpp
Labels: enhancement
